/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.airbyte.api.models.operations.async;

import static com.airbyte.api.operations.Operations.AsyncRequestOperation;

import com.airbyte.api.SDKConfiguration;
import com.airbyte.api.models.shared.TagCreateRequest;
import com.airbyte.api.operations.CreateTag;
import com.airbyte.api.utils.Headers;
import com.airbyte.api.utils.Utils;
import java.lang.Exception;
import java.util.concurrent.CompletableFuture;

public class CreateTagRequestBuilder {

    private TagCreateRequest request;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public CreateTagRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public CreateTagRequestBuilder request(TagCreateRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CompletableFuture<CreateTagResponse> call() throws Exception {
        
        AsyncRequestOperation<TagCreateRequest, CreateTagResponse> operation
              = new CreateTag.Async(sdkConfiguration, _headers);

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
