/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package airbyte_prod.public_api.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * DestinationPostgresSslModeDisable - Disable SSL.
 */
public class DestinationPostgresSslModeDisable {
    @JsonProperty("mode")
    public DestinationPostgresSslModeDisableModeEnum mode;
    public DestinationPostgresSslModeDisable withMode(DestinationPostgresSslModeDisableModeEnum mode) {
        this.mode = mode;
        return this;
    }
    
}
