/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package airbyte_prod.public_api.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SourceRecruitee - The values required to configure the source.
 */
public class SourceRecruitee {
    @JsonProperty("airbyte-source-name")public SourceRecruiteeRecruiteeEnum airbyteSourceName;
    public SourceRecruitee withAirbyteSourceName(SourceRecruiteeRecruiteeEnum airbyteSourceName) {
        this.airbyteSourceName = airbyteSourceName;
        return this;
    }
    
    /**
     * Recruitee API Key. See <a href="https://docs.recruitee.com/reference/getting-started#generate-api-token">here</a>.
     */
    @JsonProperty("api_key")public String apiKey;
    public SourceRecruitee withApiKey(String apiKey) {
        this.apiKey = apiKey;
        return this;
    }
    
    /**
     * Recruitee Company ID. You can also find this ID on the <a href="https://app.recruitee.com/#/settings/api_tokens">Recruitee API tokens page</a>.
     */
    @JsonProperty("company_id")public Long companyId;
    public SourceRecruitee withCompanyId(Long companyId) {
        this.companyId = companyId;
        return this;
    }
    
}
