/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package airbyte_prod.public_api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum SourceAmazonAdsStateFilterEnum {
    ENABLED("enabled"),
    PAUSED("paused"),
    ARCHIVED("archived");

    @JsonValue
    public final String value;

    private SourceAmazonAdsStateFilterEnum(String value) {
        this.value = value;
    }
}
