/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package airbyte_prod.public_api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SourcePocketSortByEnum - Sort retrieved items by the given criteria.
 */
public enum SourcePocketSortByEnum {
    NEWEST("newest"),
    OLDEST("oldest"),
    TITLE("title"),
    SITE("site");

    @JsonValue
    public final String value;

    private SourcePocketSortByEnum(String value) {
        this.value = value;
    }
}
