/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.airbyte.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum DestinationGcsFormatAvroApacheAvroCompressionCodecDeflateCodec {
    DEFLATE("Deflate");

    @JsonValue
    public final String value;

    private DestinationGcsFormatAvroApacheAvroCompressionCodecDeflateCodec(String value) {
        this.value = value;
    }
}
