/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.airbyte.api.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * DestinationSnowflakeLoadingMethodAzureBlobStorageStaging - Recommended for large production workloads for better speed and scalability.
 */
public class DestinationSnowflakeLoadingMethodAzureBlobStorageStaging {
    /**
     * Enter your Azure Blob Storage account name
     */
    @JsonProperty("azure_blob_storage_account_name")
    public String azureBlobStorageAccountName;
    public DestinationSnowflakeLoadingMethodAzureBlobStorageStaging withAzureBlobStorageAccountName(String azureBlobStorageAccountName) {
        this.azureBlobStorageAccountName = azureBlobStorageAccountName;
        return this;
    }
    
    /**
     * Enter your Azure Blob Storage &lt;a href="https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#container-names"&gt;container name&lt;/a&gt;
     */
    @JsonProperty("azure_blob_storage_container_name")
    public String azureBlobStorageContainerName;
    public DestinationSnowflakeLoadingMethodAzureBlobStorageStaging withAzureBlobStorageContainerName(String azureBlobStorageContainerName) {
        this.azureBlobStorageContainerName = azureBlobStorageContainerName;
        return this;
    }
    
    /**
     * Enter the Azure Blob Storage &lt;a href="https://docs.microsoft.com/en-us/azure/storage/common/storage-account-overview#storage-account-endpoints"&gt;endpoint domain name&lt;/a&gt;
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("azure_blob_storage_endpoint_domain_name")
    public String azureBlobStorageEndpointDomainName;
    public DestinationSnowflakeLoadingMethodAzureBlobStorageStaging withAzureBlobStorageEndpointDomainName(String azureBlobStorageEndpointDomainName) {
        this.azureBlobStorageEndpointDomainName = azureBlobStorageEndpointDomainName;
        return this;
    }
    
    /**
     * Enter the &lt;a href="https://docs.snowflake.com/en/user-guide/data-load-azure-config.html#option-2-generating-a-sas-token"&gt;Shared access signature&lt;/a&gt; (SAS) token to grant Snowflake limited access to objects in your Azure Blob Storage account
     */
    @JsonProperty("azure_blob_storage_sas_token")
    public String azureBlobStorageSasToken;
    public DestinationSnowflakeLoadingMethodAzureBlobStorageStaging withAzureBlobStorageSasToken(String azureBlobStorageSasToken) {
        this.azureBlobStorageSasToken = azureBlobStorageSasToken;
        return this;
    }
    
    @JsonProperty("method")
    public DestinationSnowflakeLoadingMethodAzureBlobStorageStagingMethodEnum method;
    public DestinationSnowflakeLoadingMethodAzureBlobStorageStaging withMethod(DestinationSnowflakeLoadingMethodAzureBlobStorageStagingMethodEnum method) {
        this.method = method;
        return this;
    }
    

    public DestinationSnowflakeLoadingMethodAzureBlobStorageStaging(@JsonProperty("azure_blob_storage_account_name") String azureBlobStorageAccountName, @JsonProperty("azure_blob_storage_container_name") String azureBlobStorageContainerName, @JsonProperty("azure_blob_storage_sas_token") String azureBlobStorageSasToken, @JsonProperty("method") DestinationSnowflakeLoadingMethodAzureBlobStorageStagingMethodEnum method) {
    this.azureBlobStorageAccountName = azureBlobStorageAccountName;
this.azureBlobStorageContainerName = azureBlobStorageContainerName;
this.azureBlobStorageSasToken = azureBlobStorageSasToken;
this.method = method;
  }
}
