/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.airbyte.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum DestinationSnowflakeCredentialsKeyPairAuthenticationAuthType {
    KEY_PAIR_AUTHENTICATION("Key Pair Authentication");

    @JsonValue
    public final String value;

    private DestinationSnowflakeCredentialsKeyPairAuthenticationAuthType(String value) {
        this.value = value;
    }
}
