/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.airbyte.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * DestinationAwsDatalakeFormatParquetColumnarStorageCompressionCodecOptionalEnum - The compression algorithm used to compress data.
 */
public enum DestinationAwsDatalakeFormatParquetColumnarStorageCompressionCodecOptionalEnum {
    UNCOMPRESSED("UNCOMPRESSED"),
    SNAPPY("SNAPPY"),
    GZIP("GZIP"),
    ZSTD("ZSTD");

    @JsonValue
    public final String value;

    private DestinationAwsDatalakeFormatParquetColumnarStorageCompressionCodecOptionalEnum(String value) {
        this.value = value;
    }
}
