/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.airbyte.api.models.shared;



/**
 * OAuthInputConfiguration - Arbitrary vars to pass for OAuth depending on what the source/destination spec requires.
 */

public class OAuthInputConfiguration {
    public OAuthInputConfiguration(){}
}
