/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.airbyte.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum SourceStravaStravaEnum {
    STRAVA("strava");

    @JsonValue
    public final String value;

    private SourceStravaStravaEnum(String value) {
        this.value = value;
    }
}
