/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.airbyte.api.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SourcePostgresReplicationMethodScanChangesWithUserDefinedCursor - Incrementally detects new inserts and updates using the &lt;a href="https://docs.airbyte.com/understanding-airbyte/connections/incremental-append/#user-defined-cursor"&gt;cursor column&lt;/a&gt; chosen when configuring a connection (e.g. created_at, updated_at).
 */

public class SourcePostgresReplicationMethodScanChangesWithUserDefinedCursor {
    @JsonProperty("method")
    public SourcePostgresReplicationMethodScanChangesWithUserDefinedCursorMethod method;

    public SourcePostgresReplicationMethodScanChangesWithUserDefinedCursor withMethod(SourcePostgresReplicationMethodScanChangesWithUserDefinedCursorMethod method) {
        this.method = method;
        return this;
    }
    
    public SourcePostgresReplicationMethodScanChangesWithUserDefinedCursor(@JsonProperty("method") SourcePostgresReplicationMethodScanChangesWithUserDefinedCursorMethod method) {
        this.method = method;
  }
}
