/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.airbyte.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SourceSftpCredentialsSSHKeyAuthenticationAuthMethod - Connect through ssh key
 */
public enum SourceSftpCredentialsSSHKeyAuthenticationAuthMethod {
    SSH_KEY_AUTH("SSH_KEY_AUTH");

    @JsonValue
    public final String value;

    private SourceSftpCredentialsSSHKeyAuthenticationAuthMethod(String value) {
        this.value = value;
    }
}
