/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.airbyte.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum SourceVantageVantage {
    VANTAGE("vantage");

    @JsonValue
    public final String value;

    private SourceVantageVantage(String value) {
        this.value = value;
    }
}
