/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.airbyte.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum SourceLokaliseLokalise {
    LOKALISE("lokalise");

    @JsonValue
    public final String value;

    private SourceLokaliseLokalise(String value) {
        this.value = value;
    }
}
