/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.airbyte.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SourceGnewsSortBy - This parameter allows you to choose with which type of sorting the articles should be returned. Two values  are possible:
 *   - publishedAt = sort by publication date, the articles with the most recent publication date are returned first
 *   - relevance = sort by best match to keywords, the articles with the best match are returned first
 */
public enum SourceGnewsSortBy {
    PUBLISHED_AT("publishedAt"),
    RELEVANCE("relevance");

    @JsonValue
    public final String value;

    private SourceGnewsSortBy(String value) {
        this.value = value;
    }
}
