/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.airbyte.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum SourceClickupApiClickupApi {
    CLICKUP_API("clickup-api");

    @JsonValue
    public final String value;

    private SourceClickupApiClickupApi(String value) {
        this.value = value;
    }
}
