/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.airbyte.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum SourceS3FileBasedStreamConfigFormatCSVFormatFiletype {
    CSV("csv");

    @JsonValue
    public final String value;

    private SourceS3FileBasedStreamConfigFormatCSVFormatFiletype(String value) {
        this.value = value;
    }
}
