/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.airbyte.api.models.shared;

import com.airbyte.api.utils.LazySingletonValue;
import com.airbyte.api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;


public class DestinationCumulio {

    /**
     * URL of the Cumul.io API (e.g. 'https://api.cumul.io', 'https://api.us.cumul.io', or VPC-specific API url). Defaults to 'https://api.cumul.io'.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("api_host")
    private Optional<? extends String> apiHost;

    /**
     * An API key generated in Cumul.io's platform (can be generated here: https://app.cumul.io/start/profile/integration).
     */
    @JsonProperty("api_key")
    private String apiKey;

    /**
     * The corresponding API token generated in Cumul.io's platform (can be generated here: https://app.cumul.io/start/profile/integration).
     */
    @JsonProperty("api_token")
    private String apiToken;

    @JsonProperty("destinationType")
    private Cumulio destinationType;

    public DestinationCumulio(
            @JsonProperty("api_host") Optional<? extends String> apiHost,
            @JsonProperty("api_key") String apiKey,
            @JsonProperty("api_token") String apiToken) {
        Utils.checkNotNull(apiHost, "apiHost");
        Utils.checkNotNull(apiKey, "apiKey");
        Utils.checkNotNull(apiToken, "apiToken");
        this.apiHost = apiHost;
        this.apiKey = apiKey;
        this.apiToken = apiToken;
        this.destinationType = Builder._SINGLETON_VALUE_DestinationType.value();
    }

    /**
     * URL of the Cumul.io API (e.g. 'https://api.cumul.io', 'https://api.us.cumul.io', or VPC-specific API url). Defaults to 'https://api.cumul.io'.
     */
    public Optional<? extends String> apiHost() {
        return apiHost;
    }

    /**
     * An API key generated in Cumul.io's platform (can be generated here: https://app.cumul.io/start/profile/integration).
     */
    public String apiKey() {
        return apiKey;
    }

    /**
     * The corresponding API token generated in Cumul.io's platform (can be generated here: https://app.cumul.io/start/profile/integration).
     */
    public String apiToken() {
        return apiToken;
    }

    public Cumulio destinationType() {
        return destinationType;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * URL of the Cumul.io API (e.g. 'https://api.cumul.io', 'https://api.us.cumul.io', or VPC-specific API url). Defaults to 'https://api.cumul.io'.
     */
    public DestinationCumulio withApiHost(String apiHost) {
        Utils.checkNotNull(apiHost, "apiHost");
        this.apiHost = Optional.ofNullable(apiHost);
        return this;
    }

    /**
     * URL of the Cumul.io API (e.g. 'https://api.cumul.io', 'https://api.us.cumul.io', or VPC-specific API url). Defaults to 'https://api.cumul.io'.
     */
    public DestinationCumulio withApiHost(Optional<? extends String> apiHost) {
        Utils.checkNotNull(apiHost, "apiHost");
        this.apiHost = apiHost;
        return this;
    }

    /**
     * An API key generated in Cumul.io's platform (can be generated here: https://app.cumul.io/start/profile/integration).
     */
    public DestinationCumulio withApiKey(String apiKey) {
        Utils.checkNotNull(apiKey, "apiKey");
        this.apiKey = apiKey;
        return this;
    }

    /**
     * The corresponding API token generated in Cumul.io's platform (can be generated here: https://app.cumul.io/start/profile/integration).
     */
    public DestinationCumulio withApiToken(String apiToken) {
        Utils.checkNotNull(apiToken, "apiToken");
        this.apiToken = apiToken;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DestinationCumulio other = (DestinationCumulio) o;
        return 
            java.util.Objects.deepEquals(this.apiHost, other.apiHost) &&
            java.util.Objects.deepEquals(this.apiKey, other.apiKey) &&
            java.util.Objects.deepEquals(this.apiToken, other.apiToken) &&
            java.util.Objects.deepEquals(this.destinationType, other.destinationType);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            apiHost,
            apiKey,
            apiToken,
            destinationType);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DestinationCumulio.class,
                "apiHost", apiHost,
                "apiKey", apiKey,
                "apiToken", apiToken,
                "destinationType", destinationType);
    }
    
    public final static class Builder {
 
        private Optional<? extends String> apiHost;
 
        private String apiKey;
 
        private String apiToken;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * URL of the Cumul.io API (e.g. 'https://api.cumul.io', 'https://api.us.cumul.io', or VPC-specific API url). Defaults to 'https://api.cumul.io'.
         */
        public Builder apiHost(String apiHost) {
            Utils.checkNotNull(apiHost, "apiHost");
            this.apiHost = Optional.ofNullable(apiHost);
            return this;
        }

        /**
         * URL of the Cumul.io API (e.g. 'https://api.cumul.io', 'https://api.us.cumul.io', or VPC-specific API url). Defaults to 'https://api.cumul.io'.
         */
        public Builder apiHost(Optional<? extends String> apiHost) {
            Utils.checkNotNull(apiHost, "apiHost");
            this.apiHost = apiHost;
            return this;
        }

        /**
         * An API key generated in Cumul.io's platform (can be generated here: https://app.cumul.io/start/profile/integration).
         */
        public Builder apiKey(String apiKey) {
            Utils.checkNotNull(apiKey, "apiKey");
            this.apiKey = apiKey;
            return this;
        }

        /**
         * The corresponding API token generated in Cumul.io's platform (can be generated here: https://app.cumul.io/start/profile/integration).
         */
        public Builder apiToken(String apiToken) {
            Utils.checkNotNull(apiToken, "apiToken");
            this.apiToken = apiToken;
            return this;
        }
        
        public DestinationCumulio build() {
            if (apiHost == null) {
                apiHost = _SINGLETON_VALUE_ApiHost.value();
            }
            return new DestinationCumulio(
                apiHost,
                apiKey,
                apiToken);
        }

        private static final LazySingletonValue<Optional<? extends String>> _SINGLETON_VALUE_ApiHost =
                new LazySingletonValue<>(
                        "api_host",
                        "\"https://api.cumul.io\"",
                        new TypeReference<Optional<? extends String>>() {});

        private static final LazySingletonValue<Cumulio> _SINGLETON_VALUE_DestinationType =
                new LazySingletonValue<>(
                        "destinationType",
                        "\"cumulio\"",
                        new TypeReference<Cumulio>() {});
    }
}

