/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.airbyte.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

/**
 * DetailType - Select the granularity of the information about each item.
 */
public enum DetailType {
    SIMPLE("simple"),
    COMPLETE("complete");

    @JsonValue
    private final String value;

    private DetailType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
