/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.airbyte.api.models.shared;

import com.airbyte.api.utils.LazySingletonValue;
import com.airbyte.api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * EncryptedTrustServerCertificate
 * 
 * <p>Use the certificate provided by the server without verification. (For testing purposes only!)
 */
public class EncryptedTrustServerCertificate {

    @JsonIgnore
    private Map<String, Object> additionalProperties;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private Optional<? extends DestinationMssqlName> name;

    @JsonCreator
    public EncryptedTrustServerCertificate(
            @JsonProperty("name") Optional<? extends DestinationMssqlName> name) {
        Utils.checkNotNull(name, "name");
        this.additionalProperties = new HashMap<>();
        this.name = name;
    }
    
    public EncryptedTrustServerCertificate() {
        this(Optional.empty());
    }

    @JsonAnyGetter
    public Map<String, Object> additionalProperties() {
        return additionalProperties;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<DestinationMssqlName> name() {
        return (Optional<DestinationMssqlName>) name;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    @JsonAnySetter
    public EncryptedTrustServerCertificate withAdditionalProperty(String key, Object value) {
        // note that value can be null because of the way JsonAnySetter works
        Utils.checkNotNull(key, "key");
        additionalProperties.put(key, value); 
        return this;
    }    

    public EncryptedTrustServerCertificate withAdditionalProperties(Map<String, Object> additionalProperties) {
        Utils.checkNotNull(additionalProperties, "additionalProperties");
        this.additionalProperties = additionalProperties;
        return this;
    }

    public EncryptedTrustServerCertificate withName(DestinationMssqlName name) {
        Utils.checkNotNull(name, "name");
        this.name = Optional.ofNullable(name);
        return this;
    }

    public EncryptedTrustServerCertificate withName(Optional<? extends DestinationMssqlName> name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EncryptedTrustServerCertificate other = (EncryptedTrustServerCertificate) o;
        return 
            Objects.deepEquals(this.additionalProperties, other.additionalProperties) &&
            Objects.deepEquals(this.name, other.name);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            additionalProperties,
            name);
    }
    
    @Override
    public String toString() {
        return Utils.toString(EncryptedTrustServerCertificate.class,
                "additionalProperties", additionalProperties,
                "name", name);
    }
    
    public final static class Builder {
 
        private Map<String, Object> additionalProperties = new HashMap<>();
 
        private Optional<? extends DestinationMssqlName> name;
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder additionalProperty(String key, Object value) {
            Utils.checkNotNull(key, "key");
            // we could be strict about null values (force the user
            // to pass `JsonNullable.of(null)`) but likely to be a bit 
            // annoying for additional properties building so we'll 
            // relax preconditions.
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            Utils.checkNotNull(additionalProperties, "additionalProperties");
            this.additionalProperties = additionalProperties;
            return this;
        }

        public Builder name(DestinationMssqlName name) {
            Utils.checkNotNull(name, "name");
            this.name = Optional.ofNullable(name);
            return this;
        }

        public Builder name(Optional<? extends DestinationMssqlName> name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }
        
        public EncryptedTrustServerCertificate build() {
            if (name == null) {
                name = _SINGLETON_VALUE_Name.value();
            }
            return new EncryptedTrustServerCertificate(
                name)
                .withAdditionalProperties(additionalProperties);
        }

        private static final LazySingletonValue<Optional<? extends DestinationMssqlName>> _SINGLETON_VALUE_Name =
                new LazySingletonValue<>(
                        "name",
                        "\"encrypted_trust_server_certificate\"",
                        new TypeReference<Optional<? extends DestinationMssqlName>>() {});
    }
}
