/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.airbyte.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * Environment
 * 
 * <p>The environment to use. Either sandbox or production.
 */
public enum Environment {
    SANDBOX("sandbox"),
    PRODUCTION("production");

    @JsonValue
    private final String value;

    private Environment(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<Environment> fromValue(String value) {
        for (Environment o: Environment.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

