/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.airbyte.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * Lang
 * 
 * <p>You can use lang parameter to get the output in your language. The contents of the description field will be translated. See &lt;a href="https://openweathermap.org/api/one-call-api#multi"&gt;here&lt;/a&gt; for the list of supported languages.
 */
public enum Lang {
    AF("af"),
    AL("al"),
    AR("ar"),
    AZ("az"),
    BG("bg"),
    CA("ca"),
    CZ("cz"),
    DA("da"),
    DE("de"),
    EL("el"),
    EN("en"),
    EU("eu"),
    FA("fa"),
    FI("fi"),
    FR("fr"),
    GL("gl"),
    HE("he"),
    HI("hi"),
    HR("hr"),
    HU("hu"),
    ID("id"),
    IT("it"),
    JA("ja"),
    KR("kr"),
    LA("la"),
    LT("lt"),
    MK("mk"),
    NO("no"),
    NL("nl"),
    PL("pl"),
    PT("pt"),
    PT_BR("pt_br"),
    RO("ro"),
    RU("ru"),
    SV("sv"),
    SE("se"),
    SK("sk"),
    SL("sl"),
    SP("sp"),
    ES("es"),
    SR("sr"),
    TH("th"),
    TR("tr"),
    UA("ua"),
    UK("uk"),
    VI("vi"),
    ZH_CN("zh_cn"),
    ZH_TW("zh_tw"),
    ZU("zu");

    @JsonValue
    private final String value;

    private Lang(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<Lang> fromValue(String value) {
        for (Lang o: Lang.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

