/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.airbyte.api.models.shared;

import com.airbyte.api.utils.LazySingletonValue;
import com.airbyte.api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class OAuth2 {

    @JsonProperty("auth_type")
    private SourceTicktickAuthType authType;

    /**
     * Access token for making authenticated requests; filled after complete oauth2 flow.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("client_access_token")
    private Optional<String> clientAccessToken;

    /**
     * The client ID of your Ticktick application. Read more <a
     * href="https://developer.ticktick.com/api#/openapi?id=getting-started">here</a>.
     */
    @JsonProperty("client_id")
    private String clientId;

    /**
     * The client secret of of your Ticktick application. application. Read more <a
     * href="https://developer.ticktick.com/api#/openapi?id=getting-started">here</a>.
     */
    @JsonProperty("client_secret")
    private String clientSecret;

    @JsonCreator
    public OAuth2(
            @JsonProperty("client_access_token") Optional<String> clientAccessToken,
            @JsonProperty("client_id") String clientId,
            @JsonProperty("client_secret") String clientSecret) {
        Utils.checkNotNull(clientAccessToken, "clientAccessToken");
        Utils.checkNotNull(clientId, "clientId");
        Utils.checkNotNull(clientSecret, "clientSecret");
        this.authType = Builder._SINGLETON_VALUE_AuthType.value();
        this.clientAccessToken = clientAccessToken;
        this.clientId = clientId;
        this.clientSecret = clientSecret;
    }
    
    public OAuth2(
            String clientId,
            String clientSecret) {
        this(Optional.empty(), clientId, clientSecret);
    }

    @JsonIgnore
    public SourceTicktickAuthType authType() {
        return authType;
    }

    /**
     * Access token for making authenticated requests; filled after complete oauth2 flow.
     */
    @JsonIgnore
    public Optional<String> clientAccessToken() {
        return clientAccessToken;
    }

    /**
     * The client ID of your Ticktick application. Read more <a
     * href="https://developer.ticktick.com/api#/openapi?id=getting-started">here</a>.
     */
    @JsonIgnore
    public String clientId() {
        return clientId;
    }

    /**
     * The client secret of of your Ticktick application. application. Read more <a
     * href="https://developer.ticktick.com/api#/openapi?id=getting-started">here</a>.
     */
    @JsonIgnore
    public String clientSecret() {
        return clientSecret;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Access token for making authenticated requests; filled after complete oauth2 flow.
     */
    public OAuth2 withClientAccessToken(String clientAccessToken) {
        Utils.checkNotNull(clientAccessToken, "clientAccessToken");
        this.clientAccessToken = Optional.ofNullable(clientAccessToken);
        return this;
    }


    /**
     * Access token for making authenticated requests; filled after complete oauth2 flow.
     */
    public OAuth2 withClientAccessToken(Optional<String> clientAccessToken) {
        Utils.checkNotNull(clientAccessToken, "clientAccessToken");
        this.clientAccessToken = clientAccessToken;
        return this;
    }

    /**
     * The client ID of your Ticktick application. Read more <a
     * href="https://developer.ticktick.com/api#/openapi?id=getting-started">here</a>.
     */
    public OAuth2 withClientId(String clientId) {
        Utils.checkNotNull(clientId, "clientId");
        this.clientId = clientId;
        return this;
    }

    /**
     * The client secret of of your Ticktick application. application. Read more <a
     * href="https://developer.ticktick.com/api#/openapi?id=getting-started">here</a>.
     */
    public OAuth2 withClientSecret(String clientSecret) {
        Utils.checkNotNull(clientSecret, "clientSecret");
        this.clientSecret = clientSecret;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OAuth2 other = (OAuth2) o;
        return 
            Utils.enhancedDeepEquals(this.authType, other.authType) &&
            Utils.enhancedDeepEquals(this.clientAccessToken, other.clientAccessToken) &&
            Utils.enhancedDeepEquals(this.clientId, other.clientId) &&
            Utils.enhancedDeepEquals(this.clientSecret, other.clientSecret);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            authType, clientAccessToken, clientId,
            clientSecret);
    }
    
    @Override
    public String toString() {
        return Utils.toString(OAuth2.class,
                "authType", authType,
                "clientAccessToken", clientAccessToken,
                "clientId", clientId,
                "clientSecret", clientSecret);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> clientAccessToken = Optional.empty();

        private String clientId;

        private String clientSecret;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Access token for making authenticated requests; filled after complete oauth2 flow.
         */
        public Builder clientAccessToken(String clientAccessToken) {
            Utils.checkNotNull(clientAccessToken, "clientAccessToken");
            this.clientAccessToken = Optional.ofNullable(clientAccessToken);
            return this;
        }

        /**
         * Access token for making authenticated requests; filled after complete oauth2 flow.
         */
        public Builder clientAccessToken(Optional<String> clientAccessToken) {
            Utils.checkNotNull(clientAccessToken, "clientAccessToken");
            this.clientAccessToken = clientAccessToken;
            return this;
        }


        /**
         * The client ID of your Ticktick application. Read more <a
         * href="https://developer.ticktick.com/api#/openapi?id=getting-started">here</a>.
         */
        public Builder clientId(String clientId) {
            Utils.checkNotNull(clientId, "clientId");
            this.clientId = clientId;
            return this;
        }


        /**
         * The client secret of of your Ticktick application. application. Read more <a
         * href="https://developer.ticktick.com/api#/openapi?id=getting-started">here</a>.
         */
        public Builder clientSecret(String clientSecret) {
            Utils.checkNotNull(clientSecret, "clientSecret");
            this.clientSecret = clientSecret;
            return this;
        }

        public OAuth2 build() {

            return new OAuth2(
                clientAccessToken, clientId, clientSecret);
        }


        private static final LazySingletonValue<SourceTicktickAuthType> _SINGLETON_VALUE_AuthType =
                new LazySingletonValue<>(
                        "auth_type",
                        "\"Oauth\"",
                        new TypeReference<SourceTicktickAuthType>() {});
    }
}
