/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.airbyte.api.models.shared;

import com.airbyte.api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;

/**
 * OrganizationOAuthCredentialsRequest
 * 
 * <p>POST body for creating/updating organization level OAuth credentials
 */
public class OrganizationOAuthCredentialsRequest {

    /**
     * Whether you're setting this override for a source or destination
     */
    @JsonProperty("actorType")
    private ActorTypeEnum actorType;

    /**
     * The values required to configure the source.
     */
    @JsonProperty("configuration")
    private Object configuration;

    /**
     * The name of the source i.e. google-ads
     */
    @JsonProperty("name")
    private String name;

    @JsonCreator
    public OrganizationOAuthCredentialsRequest(
            @JsonProperty("actorType") ActorTypeEnum actorType,
            @JsonProperty("configuration") Object configuration,
            @JsonProperty("name") String name) {
        Utils.checkNotNull(actorType, "actorType");
        Utils.checkNotNull(configuration, "configuration");
        Utils.checkNotNull(name, "name");
        this.actorType = actorType;
        this.configuration = configuration;
        this.name = name;
    }

    /**
     * Whether you're setting this override for a source or destination
     */
    @JsonIgnore
    public ActorTypeEnum actorType() {
        return actorType;
    }

    /**
     * The values required to configure the source.
     */
    @JsonIgnore
    public Object configuration() {
        return configuration;
    }

    /**
     * The name of the source i.e. google-ads
     */
    @JsonIgnore
    public String name() {
        return name;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * Whether you're setting this override for a source or destination
     */
    public OrganizationOAuthCredentialsRequest withActorType(ActorTypeEnum actorType) {
        Utils.checkNotNull(actorType, "actorType");
        this.actorType = actorType;
        return this;
    }

    /**
     * The values required to configure the source.
     */
    public OrganizationOAuthCredentialsRequest withConfiguration(Object configuration) {
        Utils.checkNotNull(configuration, "configuration");
        this.configuration = configuration;
        return this;
    }

    /**
     * The name of the source i.e. google-ads
     */
    public OrganizationOAuthCredentialsRequest withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OrganizationOAuthCredentialsRequest other = (OrganizationOAuthCredentialsRequest) o;
        return 
            Objects.deepEquals(this.actorType, other.actorType) &&
            Objects.deepEquals(this.configuration, other.configuration) &&
            Objects.deepEquals(this.name, other.name);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            actorType,
            configuration,
            name);
    }
    
    @Override
    public String toString() {
        return Utils.toString(OrganizationOAuthCredentialsRequest.class,
                "actorType", actorType,
                "configuration", configuration,
                "name", name);
    }
    
    public final static class Builder {
 
        private ActorTypeEnum actorType;
 
        private Object configuration;
 
        private String name;
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Whether you're setting this override for a source or destination
         */
        public Builder actorType(ActorTypeEnum actorType) {
            Utils.checkNotNull(actorType, "actorType");
            this.actorType = actorType;
            return this;
        }

        /**
         * The values required to configure the source.
         */
        public Builder configuration(Object configuration) {
            Utils.checkNotNull(configuration, "configuration");
            this.configuration = configuration;
            return this;
        }

        /**
         * The name of the source i.e. google-ads
         */
        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }
        
        public OrganizationOAuthCredentialsRequest build() {
            return new OrganizationOAuthCredentialsRequest(
                actorType,
                configuration,
                name);
        }
    }
}
