/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.airbyte.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum SourceMysqlTunnelMethod {
    NO_TUNNEL("NO_TUNNEL");

    @JsonValue
    private final String value;

    private SourceMysqlTunnelMethod(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<SourceMysqlTunnelMethod> fromValue(String value) {
        for (SourceMysqlTunnelMethod o: SourceMysqlTunnelMethod.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

