/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.airbyte.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

/**
 * SourceZohoCrmEnvironment - Please choose the environment
 */
public enum SourceZohoCrmEnvironment {
    PRODUCTION("Production"),
    DEVELOPER("Developer"),
    SANDBOX("Sandbox");

    @JsonValue
    private final String value;

    private SourceZohoCrmEnvironment(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
