/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.airbyte.api.models.shared;

import com.airbyte.api.utils.OneOfDeserializer;
import com.airbyte.api.utils.TypedObject;
import com.airbyte.api.utils.Utils.JsonShape;
import com.airbyte.api.utils.Utils.TypeReferenceWithShape;
import com.airbyte.api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;

@JsonDeserialize(using = SourceMicrosoftSharepointDeliveryMethod._Deserializer.class)
public class SourceMicrosoftSharepointDeliveryMethod {

    @JsonValue
    private TypedObject value;
    
    private SourceMicrosoftSharepointDeliveryMethod(TypedObject value) {
        this.value = value;
    }

    public static SourceMicrosoftSharepointDeliveryMethod of(SourceMicrosoftSharepointReplicateRecords value) {
        Utils.checkNotNull(value, "value");
        return new SourceMicrosoftSharepointDeliveryMethod(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<SourceMicrosoftSharepointReplicateRecords>(){}));
    }

    public static SourceMicrosoftSharepointDeliveryMethod of(SourceMicrosoftSharepointCopyRawFiles value) {
        Utils.checkNotNull(value, "value");
        return new SourceMicrosoftSharepointDeliveryMethod(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<SourceMicrosoftSharepointCopyRawFiles>(){}));
    }
    
    /**
     * Returns an instance of one of these types:
     * <ul>
     * <li>{@code com.airbyte.api.models.shared.SourceMicrosoftSharepointReplicateRecords}</li>
     * <li>{@code com.airbyte.api.models.shared.SourceMicrosoftSharepointCopyRawFiles}</li>
     * </ul>
     * 
     * <p>Use {@code instanceof} to determine what type is returned. For example:
     * 
     * <pre>
     * if (obj.value() instanceof String) {
     *     String answer = (String) obj.value();
     *     System.out.println("answer=" + answer);
     * }
     * </pre>
     * 
     * @return value of oneOf type
     **/ 
    public java.lang.Object value() {
        return value.value();
    }    
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SourceMicrosoftSharepointDeliveryMethod other = (SourceMicrosoftSharepointDeliveryMethod) o;
        return Objects.deepEquals(this.value.value(), other.value.value()); 
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<SourceMicrosoftSharepointDeliveryMethod> {

        public _Deserializer() {
            super(SourceMicrosoftSharepointDeliveryMethod.class, false,
                  TypeReferenceWithShape.of(new TypeReference<SourceMicrosoftSharepointCopyRawFiles>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<SourceMicrosoftSharepointReplicateRecords>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(SourceMicrosoftSharepointDeliveryMethod.class,
                "value", value);
    }
 
}

