/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.airbyte.api.models.shared;

import com.airbyte.api.utils.LazySingletonValue;
import com.airbyte.api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;

public class SourceTremendous {

    /**
     * API key to use. You can generate an API key through the Tremendous dashboard under Team Settings &gt; Developers. Save the key once you’ve generated it.
     */
    @JsonProperty("api_key")
    private String apiKey;

    @JsonProperty("environment")
    private SourceTremendousEnvironment environment;

    @JsonProperty("sourceType")
    private Tremendous sourceType;

    @JsonCreator
    public SourceTremendous(
            @JsonProperty("api_key") String apiKey,
            @JsonProperty("environment") SourceTremendousEnvironment environment) {
        Utils.checkNotNull(apiKey, "apiKey");
        Utils.checkNotNull(environment, "environment");
        this.apiKey = apiKey;
        this.environment = environment;
        this.sourceType = Builder._SINGLETON_VALUE_SourceType.value();
    }

    /**
     * API key to use. You can generate an API key through the Tremendous dashboard under Team Settings &gt; Developers. Save the key once you’ve generated it.
     */
    @JsonIgnore
    public String apiKey() {
        return apiKey;
    }

    @JsonIgnore
    public SourceTremendousEnvironment environment() {
        return environment;
    }

    @JsonIgnore
    public Tremendous sourceType() {
        return sourceType;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * API key to use. You can generate an API key through the Tremendous dashboard under Team Settings &gt; Developers. Save the key once you’ve generated it.
     */
    public SourceTremendous withApiKey(String apiKey) {
        Utils.checkNotNull(apiKey, "apiKey");
        this.apiKey = apiKey;
        return this;
    }

    public SourceTremendous withEnvironment(SourceTremendousEnvironment environment) {
        Utils.checkNotNull(environment, "environment");
        this.environment = environment;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SourceTremendous other = (SourceTremendous) o;
        return 
            Objects.deepEquals(this.apiKey, other.apiKey) &&
            Objects.deepEquals(this.environment, other.environment) &&
            Objects.deepEquals(this.sourceType, other.sourceType);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            apiKey,
            environment,
            sourceType);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SourceTremendous.class,
                "apiKey", apiKey,
                "environment", environment,
                "sourceType", sourceType);
    }
    
    public final static class Builder {
 
        private String apiKey;
 
        private SourceTremendousEnvironment environment;
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * API key to use. You can generate an API key through the Tremendous dashboard under Team Settings &gt; Developers. Save the key once you’ve generated it.
         */
        public Builder apiKey(String apiKey) {
            Utils.checkNotNull(apiKey, "apiKey");
            this.apiKey = apiKey;
            return this;
        }

        public Builder environment(SourceTremendousEnvironment environment) {
            Utils.checkNotNull(environment, "environment");
            this.environment = environment;
            return this;
        }
        
        public SourceTremendous build() {
            return new SourceTremendous(
                apiKey,
                environment);
        }

        private static final LazySingletonValue<Tremendous> _SINGLETON_VALUE_SourceType =
                new LazySingletonValue<>(
                        "sourceType",
                        "\"tremendous\"",
                        new TypeReference<Tremendous>() {});
    }
}
