/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.airbyte.api.models.shared;


import com.airbyte.api.utils.OneOfDeserializer;
import com.airbyte.api.utils.TypedObject;
import com.airbyte.api.utils.Utils.JsonShape;
import com.airbyte.api.utils.Utils.TypeReferenceWithShape;
import com.airbyte.api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;

/**
 * SourceGoogleDriveFormat - The configuration options that are used to alter how to read incoming files that deviate from the standard formatting.
 */

@JsonDeserialize(using = SourceGoogleDriveFormat._Deserializer.class)
public class SourceGoogleDriveFormat {

    @JsonValue
    private TypedObject value;
    
    private SourceGoogleDriveFormat(TypedObject value) {
        this.value = value;
    }

    public static SourceGoogleDriveFormat of(SourceGoogleDriveAvroFormat value) {
        Utils.checkNotNull(value, "value");
        return new SourceGoogleDriveFormat(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<SourceGoogleDriveAvroFormat>(){}));
    }

    public static SourceGoogleDriveFormat of(SourceGoogleDriveCSVFormat value) {
        Utils.checkNotNull(value, "value");
        return new SourceGoogleDriveFormat(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<SourceGoogleDriveCSVFormat>(){}));
    }

    public static SourceGoogleDriveFormat of(SourceGoogleDriveJsonlFormat value) {
        Utils.checkNotNull(value, "value");
        return new SourceGoogleDriveFormat(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<SourceGoogleDriveJsonlFormat>(){}));
    }

    public static SourceGoogleDriveFormat of(SourceGoogleDriveParquetFormat value) {
        Utils.checkNotNull(value, "value");
        return new SourceGoogleDriveFormat(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<SourceGoogleDriveParquetFormat>(){}));
    }

    public static SourceGoogleDriveFormat of(SourceGoogleDriveDocumentFileTypeFormatExperimental value) {
        Utils.checkNotNull(value, "value");
        return new SourceGoogleDriveFormat(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<SourceGoogleDriveDocumentFileTypeFormatExperimental>(){}));
    }
    
    /**
     * Returns an instance of one of these types:
     * <ul>
     * <li>{@code com.airbyte.api.models.shared.SourceGoogleDriveAvroFormat}</li>
     * <li>{@code com.airbyte.api.models.shared.SourceGoogleDriveCSVFormat}</li>
     * <li>{@code com.airbyte.api.models.shared.SourceGoogleDriveJsonlFormat}</li>
     * <li>{@code com.airbyte.api.models.shared.SourceGoogleDriveParquetFormat}</li>
     * <li>{@code com.airbyte.api.models.shared.SourceGoogleDriveDocumentFileTypeFormatExperimental}</li>
     * </ul>
     * 
     * <p>Use {@code instanceof} to determine what type is returned. For example:
     * 
     * <pre>
     * if (obj.value() instanceof String) {
     *     String answer = (String) obj.value();
     *     System.out.println("answer=" + answer);
     * }
     * </pre>
     * 
     * @return value of oneOf type
     **/ 
    public java.lang.Object value() {
        return value.value();
    }    
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SourceGoogleDriveFormat other = (SourceGoogleDriveFormat) o;
        return Objects.deepEquals(this.value.value(), other.value.value()); 
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<SourceGoogleDriveFormat> {

        public _Deserializer() {
            super(SourceGoogleDriveFormat.class, false,
                  TypeReferenceWithShape.of(new TypeReference<SourceGoogleDriveCSVFormat>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<SourceGoogleDriveDocumentFileTypeFormatExperimental>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<SourceGoogleDriveParquetFormat>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<SourceGoogleDriveAvroFormat>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<SourceGoogleDriveJsonlFormat>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(SourceGoogleDriveFormat.class,
                "value", value);
    }
 
}
