/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.airbyte.api.models.shared;

import com.airbyte.api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;

import java.time.OffsetDateTime;
import java.time.LocalDate;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.airbyte.api.utils.TypedObject;
import com.airbyte.api.utils.Utils.JsonShape;

/**
 * SourceSftpBulkFormat - The configuration options that are used to alter how to read incoming files that deviate from the standard formatting.
 */

@JsonDeserialize(using = SourceSftpBulkFormat._Deserializer.class)
public class SourceSftpBulkFormat {

    @com.fasterxml.jackson.annotation.JsonValue
    private TypedObject value;
    
    private SourceSftpBulkFormat(TypedObject value) {
        this.value = value;
    }

    public static SourceSftpBulkFormat of(SourceSftpBulkAvroFormat value) {
        Utils.checkNotNull(value, "value");
        return new SourceSftpBulkFormat(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<SourceSftpBulkAvroFormat>(){}));
    }

    public static SourceSftpBulkFormat of(SourceSftpBulkCSVFormat value) {
        Utils.checkNotNull(value, "value");
        return new SourceSftpBulkFormat(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<SourceSftpBulkCSVFormat>(){}));
    }

    public static SourceSftpBulkFormat of(SourceSftpBulkJsonlFormat value) {
        Utils.checkNotNull(value, "value");
        return new SourceSftpBulkFormat(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<SourceSftpBulkJsonlFormat>(){}));
    }

    public static SourceSftpBulkFormat of(SourceSftpBulkParquetFormat value) {
        Utils.checkNotNull(value, "value");
        return new SourceSftpBulkFormat(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<SourceSftpBulkParquetFormat>(){}));
    }

    public static SourceSftpBulkFormat of(SourceSftpBulkUnstructuredDocumentFormat value) {
        Utils.checkNotNull(value, "value");
        return new SourceSftpBulkFormat(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<SourceSftpBulkUnstructuredDocumentFormat>(){}));
    }

    public static SourceSftpBulkFormat of(SourceSftpBulkExcelFormat value) {
        Utils.checkNotNull(value, "value");
        return new SourceSftpBulkFormat(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<SourceSftpBulkExcelFormat>(){}));
    }
    
    /**
     * Returns an instance of one of these types:
     * <ul>
     * <li>{@code SourceSftpBulkAvroFormat}</li>
     * <li>{@code SourceSftpBulkCSVFormat}</li>
     * <li>{@code SourceSftpBulkJsonlFormat}</li>
     * <li>{@code SourceSftpBulkParquetFormat}</li>
     * <li>{@code SourceSftpBulkUnstructuredDocumentFormat}</li>
     * <li>{@code SourceSftpBulkExcelFormat}</li>
     * </ul>
     * 
     * <p>Use {@code instanceof} to determine what type is returned. For example:
     * 
     * <pre>
     * if (obj.value() instanceof String) {
     *     String answer = (String) obj.value();
     *     System.out.println("answer=" + answer);
     * }
     * </pre>
     * 
     * @return value of oneOf type
     **/ 
    public java.lang.Object value() {
        return value.value();
    }    
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SourceSftpBulkFormat other = (SourceSftpBulkFormat) o;
        return java.util.Objects.deepEquals(this.value.value(), other.value.value()); 
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends com.airbyte.api.utils.OneOfDeserializer<SourceSftpBulkFormat> {

        public _Deserializer() {
            super(SourceSftpBulkFormat.class,
                  Utils.TypeReferenceWithShape.of(new TypeReference<SourceSftpBulkAvroFormat>() {}, Utils.JsonShape.DEFAULT),
                  Utils.TypeReferenceWithShape.of(new TypeReference<SourceSftpBulkCSVFormat>() {}, Utils.JsonShape.DEFAULT),
                  Utils.TypeReferenceWithShape.of(new TypeReference<SourceSftpBulkJsonlFormat>() {}, Utils.JsonShape.DEFAULT),
                  Utils.TypeReferenceWithShape.of(new TypeReference<SourceSftpBulkParquetFormat>() {}, Utils.JsonShape.DEFAULT),
                  Utils.TypeReferenceWithShape.of(new TypeReference<SourceSftpBulkUnstructuredDocumentFormat>() {}, Utils.JsonShape.DEFAULT),
                  Utils.TypeReferenceWithShape.of(new TypeReference<SourceSftpBulkExcelFormat>() {}, Utils.JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(SourceSftpBulkFormat.class,
                "value", value);
    }
 
}
