/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.airbyte.api.models.shared;


import com.airbyte.api.utils.OneOfDeserializer;
import com.airbyte.api.utils.TypedObject;
import com.airbyte.api.utils.Utils.JsonShape;
import com.airbyte.api.utils.Utils.TypeReferenceWithShape;
import com.airbyte.api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;

/**
 * SSLModes - SSL connection modes. 
 *  &lt;b&gt;disable&lt;/b&gt; - Chose this mode to disable encryption of communication between Airbyte and destination database
 *  &lt;b&gt;allow&lt;/b&gt; - Chose this mode to enable encryption only when required by the source database
 *  &lt;b&gt;prefer&lt;/b&gt; - Chose this mode to allow unencrypted connection only if the source database does not support encryption
 *  &lt;b&gt;require&lt;/b&gt; - Chose this mode to always require encryption. If the source database server does not support encryption, connection will fail
 *   &lt;b&gt;verify-ca&lt;/b&gt; - Chose this mode to always require encryption and to verify that the source database server has a valid SSL certificate
 *   &lt;b&gt;verify-full&lt;/b&gt; - This is the most secure mode. Chose this mode to always require encryption and to verify the identity of the source database server
 *  See more information - &lt;a href="https://jdbc.postgresql.org/documentation/head/ssl-client.html"&gt; in the docs&lt;/a&gt;.
 */

@JsonDeserialize(using = SSLModes._Deserializer.class)
public class SSLModes {

    @JsonValue
    private TypedObject value;
    
    private SSLModes(TypedObject value) {
        this.value = value;
    }

    public static SSLModes of(Disable value) {
        Utils.checkNotNull(value, "value");
        return new SSLModes(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<Disable>(){}));
    }

    public static SSLModes of(Allow value) {
        Utils.checkNotNull(value, "value");
        return new SSLModes(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<Allow>(){}));
    }

    public static SSLModes of(Prefer value) {
        Utils.checkNotNull(value, "value");
        return new SSLModes(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<Prefer>(){}));
    }

    public static SSLModes of(Require value) {
        Utils.checkNotNull(value, "value");
        return new SSLModes(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<Require>(){}));
    }

    public static SSLModes of(VerifyCa value) {
        Utils.checkNotNull(value, "value");
        return new SSLModes(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<VerifyCa>(){}));
    }

    public static SSLModes of(VerifyFull value) {
        Utils.checkNotNull(value, "value");
        return new SSLModes(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<VerifyFull>(){}));
    }
    
    /**
     * Returns an instance of one of these types:
     * <ul>
     * <li>{@code com.airbyte.api.models.shared.Disable}</li>
     * <li>{@code com.airbyte.api.models.shared.Allow}</li>
     * <li>{@code com.airbyte.api.models.shared.Prefer}</li>
     * <li>{@code com.airbyte.api.models.shared.Require}</li>
     * <li>{@code com.airbyte.api.models.shared.VerifyCa}</li>
     * <li>{@code com.airbyte.api.models.shared.VerifyFull}</li>
     * </ul>
     * 
     * <p>Use {@code instanceof} to determine what type is returned. For example:
     * 
     * <pre>
     * if (obj.value() instanceof String) {
     *     String answer = (String) obj.value();
     *     System.out.println("answer=" + answer);
     * }
     * </pre>
     * 
     * @return value of oneOf type
     **/ 
    public java.lang.Object value() {
        return value.value();
    }    
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SSLModes other = (SSLModes) o;
        return Objects.deepEquals(this.value.value(), other.value.value()); 
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<SSLModes> {

        public _Deserializer() {
            super(SSLModes.class, false,
                  TypeReferenceWithShape.of(new TypeReference<com.airbyte.api.models.shared.VerifyFull>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<com.airbyte.api.models.shared.VerifyCa>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<com.airbyte.api.models.shared.Require>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<com.airbyte.api.models.shared.Prefer>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<com.airbyte.api.models.shared.Allow>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<com.airbyte.api.models.shared.Disable>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(SSLModes.class,
                "value", value);
    }
 
}
