/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.airbyte.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * UpdateMode
 * 
 * <p>How to update the data in the destination.
 */
public enum UpdateMode {
    INSERT("INSERT"),
    UPDATE("UPDATE"),
    UPSERT("UPSERT"),
    DELETE("DELETE");

    @JsonValue
    private final String value;

    private UpdateMode(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<UpdateMode> fromValue(String value) {
        for (UpdateMode o: UpdateMode.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

