/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.airbyte.api.models.shared;

import com.airbyte.api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * ValidAdStatuses - An enumeration.
 */
public enum ValidAdStatuses {
    ACTIVE("ACTIVE"),
    ADSET_PAUSED("ADSET_PAUSED"),
    ARCHIVED("ARCHIVED"),
    CAMPAIGN_PAUSED("CAMPAIGN_PAUSED"),
    DELETED("DELETED"),
    DISAPPROVED("DISAPPROVED"),
    IN_PROCESS("IN_PROCESS"),
    PAUSED("PAUSED"),
    PENDING_BILLING_INFO("PENDING_BILLING_INFO"),
    PENDING_REVIEW("PENDING_REVIEW"),
    PREAPPROVED("PREAPPROVED"),
    WITH_ISSUES("WITH_ISSUES");

    @JsonValue
    private final String value;

    private ValidAdStatuses(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
