description = 'public-api Spring Boot Starter'

// Publishing configuration overrides
ext {
    publishingConfig = [
        groupId: rootProject.group,
        artifactId: 'api-spring-boot-starter',
        version: rootProject.version,
        name: 'Airbyte Java SDK - Spring Boot Starter',
        description: 'Spring Boot starter for the Airbyte Java SDK.',
    ]
}

dependencies {
    api project(':')
    api project(':api-spring-boot-autoconfigure')
    api "org.springframework.boot:spring-boot-starter:${rootProject.springBootVersion}"
}

jar {
    archiveBaseName = 'api-spring-boot-starter'
}