/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package airbyte_prod.api.models.operations;

import airbyte_prod.api.utils.SpeakeasyMetadata;

public class OauthCallbackRequest {
    /**
     * Query parameters. Should contain state and code.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=queryParams")
    public java.util.Map<String, String> queryParams;
    public OauthCallbackRequest withQueryParams(java.util.Map<String, String> queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
}
