/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.airbyte.api;

import static com.airbyte.api.operations.Operations.RequestlessOperation;

import com.airbyte.api.models.operations.GetHealthCheckRequestBuilder;
import com.airbyte.api.models.operations.GetHealthCheckResponse;
import com.airbyte.api.operations.GetHealthCheckOperation;
import java.lang.Exception;
import java.util.List;
import java.util.Optional;


public class Health {
    private final SDKConfiguration sdkConfiguration;

    Health(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    /**
     * Health Check
     * 
     * @return The call builder
     */
    public GetHealthCheckRequestBuilder getHealthCheck() {
        return new GetHealthCheckRequestBuilder(sdkConfiguration);
    }

    /**
     * Health Check
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public GetHealthCheckResponse getHealthCheckDirect() throws Exception {
        RequestlessOperation<GetHealthCheckResponse> operation
            = new GetHealthCheckOperation( sdkConfiguration);
        return operation.handleResponse(operation.doRequest());
    }

}
