workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://raw.githubusercontent.com/airbytehq/airbyte-api-python-sdk/main/airbyte-api.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/airbyte/airbyte-prod/my-source
targets:
    airbyte-api:
        target: java
        source: my-source
        publish:
            java:
                ossrhUsername: ${{ secrets.OSSRH_USERNAME }}
                ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
                gpgSecretKey: ${{ secrets.GPG_SECRET_KEY }}
                gpgPassPhrase: ${{ secrets.GPG_PASSPHRASE }}
