/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package airbyte_prod.api.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SourceTrustpilot - The values required to configure the source.
 */
public class SourceTrustpilot {
    /**
     * The names of business units which shall be synchronized. Some streams e.g. configured_business_units or private_reviews use this configuration.
     */
    @JsonProperty("business_units")
    public String[] businessUnits;
    public SourceTrustpilot withBusinessUnits(String[] businessUnits) {
        this.businessUnits = businessUnits;
        return this;
    }
    
    @JsonProperty("credentials")
    public Object credentials;
    public SourceTrustpilot withCredentials(Object credentials) {
        this.credentials = credentials;
        return this;
    }
    
    @JsonProperty("sourceType")
    public SourceTrustpilotTrustpilotEnum sourceType;
    public SourceTrustpilot withSourceType(SourceTrustpilotTrustpilotEnum sourceType) {
        this.sourceType = sourceType;
        return this;
    }
    
    /**
     * For streams with sync. method incremental the start date time to be used
     */
    @JsonProperty("start_date")
    public String startDate;
    public SourceTrustpilot withStartDate(String startDate) {
        this.startDate = startDate;
        return this;
    }
    
}
