/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.airbyte.api.models.operations;

import static com.airbyte.api.operations.Operations.RequestOperation;

import com.airbyte.api.SDKConfiguration;
import com.airbyte.api.models.shared.ConnectionCreateRequest;
import com.airbyte.api.operations.CreateConnectionOperation;
import com.airbyte.api.utils.Utils;
import java.lang.Exception;

public class CreateConnectionRequestBuilder {

    private ConnectionCreateRequest request;
    private final SDKConfiguration sdkConfiguration;

    public CreateConnectionRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public CreateConnectionRequestBuilder request(ConnectionCreateRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CreateConnectionResponse call() throws Exception {
        
        RequestOperation<ConnectionCreateRequest, CreateConnectionResponse> operation
              = new CreateConnectionOperation( sdkConfiguration);

        return operation.handleResponse(operation.doRequest(request));
    }
}
