/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.airbyte.api.models.operations;

import static com.airbyte.api.operations.Operations.RequestOperation;

import com.airbyte.api.SDKConfiguration;
import com.airbyte.api.operations.DeleteTagOperation;
import com.airbyte.api.utils.Utils;
import java.lang.Exception;

public class DeleteTagRequestBuilder {

    private DeleteTagRequest request;
    private final SDKConfiguration sdkConfiguration;

    public DeleteTagRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public DeleteTagRequestBuilder request(DeleteTagRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public DeleteTagResponse call() throws Exception {
        
        RequestOperation<DeleteTagRequest, DeleteTagResponse> operation
              = new DeleteTagOperation( sdkConfiguration);

        return operation.handleResponse(operation.doRequest(request));
    }
}
