/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.airbyte.api.models.operations;

import com.airbyte.api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.net.http.HttpResponse;
import java.util.Optional;


public class ListDestinationsResponse implements com.airbyte.api.utils.Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * Successful operation
     */
    private Optional<? extends com.airbyte.api.models.shared.DestinationsResponse> destinationsResponse;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    public ListDestinationsResponse(
            String contentType,
            Optional<? extends com.airbyte.api.models.shared.DestinationsResponse> destinationsResponse,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(destinationsResponse, "destinationsResponse");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.contentType = contentType;
        this.destinationsResponse = destinationsResponse;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
    }

    /**
     * HTTP response content type for this operation
     */
    public String contentType() {
        return contentType;
    }

    /**
     * Successful operation
     */
    public Optional<? extends com.airbyte.api.models.shared.DestinationsResponse> destinationsResponse() {
        return destinationsResponse;
    }

    /**
     * HTTP response status code for this operation
     */
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public ListDestinationsResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * Successful operation
     */
    public ListDestinationsResponse withDestinationsResponse(com.airbyte.api.models.shared.DestinationsResponse destinationsResponse) {
        Utils.checkNotNull(destinationsResponse, "destinationsResponse");
        this.destinationsResponse = Optional.ofNullable(destinationsResponse);
        return this;
    }

    /**
     * Successful operation
     */
    public ListDestinationsResponse withDestinationsResponse(Optional<? extends com.airbyte.api.models.shared.DestinationsResponse> destinationsResponse) {
        Utils.checkNotNull(destinationsResponse, "destinationsResponse");
        this.destinationsResponse = destinationsResponse;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public ListDestinationsResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public ListDestinationsResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListDestinationsResponse other = (ListDestinationsResponse) o;
        return 
            java.util.Objects.deepEquals(this.contentType, other.contentType) &&
            java.util.Objects.deepEquals(this.destinationsResponse, other.destinationsResponse) &&
            java.util.Objects.deepEquals(this.statusCode, other.statusCode) &&
            java.util.Objects.deepEquals(this.rawResponse, other.rawResponse);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            contentType,
            destinationsResponse,
            statusCode,
            rawResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListDestinationsResponse.class,
                "contentType", contentType,
                "destinationsResponse", destinationsResponse,
                "statusCode", statusCode,
                "rawResponse", rawResponse);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Optional<? extends com.airbyte.api.models.shared.DestinationsResponse> destinationsResponse = Optional.empty();
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * Successful operation
         */
        public Builder destinationsResponse(com.airbyte.api.models.shared.DestinationsResponse destinationsResponse) {
            Utils.checkNotNull(destinationsResponse, "destinationsResponse");
            this.destinationsResponse = Optional.ofNullable(destinationsResponse);
            return this;
        }

        /**
         * Successful operation
         */
        public Builder destinationsResponse(Optional<? extends com.airbyte.api.models.shared.DestinationsResponse> destinationsResponse) {
            Utils.checkNotNull(destinationsResponse, "destinationsResponse");
            this.destinationsResponse = destinationsResponse;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }
        
        public ListDestinationsResponse build() {
            return new ListDestinationsResponse(
                contentType,
                destinationsResponse,
                statusCode,
                rawResponse);
        }
    }
}

