name: Publish
"on":
  push:
    branches:
      - main
    paths:
      - RELEASES.md
jobs:
  publish:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@v14
    with:
      create_release: true
      publish_java: true
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
      ossrh_username: ${{ secrets.MAVEN_USERNAME }}
      ossrh_password: ${{ secrets.MAVEN_PASSWORD }}
      java_gpg_secret_key: ${{ secrets.GPG_SECRET_KEY }}
      java_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      
