name: Publish
"on":
    push:
        branches:
            - main
        paths:
            - RELEASES.md
jobs:
    publish:
        uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@v15
        secrets:
            github_access_token: ${{ secrets.GITHUB_TOKEN }}
            java_gpg_passphrase: ${{ secrets.JAVA_GPG_PASSPHRASE }}
            java_gpg_secret_key: ${{ secrets.JAVA_GPG_SECRET_KEY }}
            ossrh_password: ${{ secrets.OSSRH_PASSWORD }}
            speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
